using DeepNaiCore.HttpCode;
using HttpCodeLib;
using MyTools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DeepNaiCore.TbUnionService
{
    class TbUnionApi
    {
        public static int APP_MEDIA_TYPE = 2;
        public static int WEB_MEDIA_TYPE = 1;
        public static int GUIDE_MEDIA_TYPE = 3;
        private static ListBox LogDisplayedInForm_;

        public static ListBox LogDisplayedInForm { get => LogDisplayedInForm_; set => LogDisplayedInForm_ = value; }

        /// <summary>
        /// 获取指定类别下的所有媒体
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="mediaType">媒体类别1 web 2 app 3 guide</param>
        /// <param name="page">默认为1</param>
        /// <param name="pageSize">默认为40</param>
        /// <returns></returns>
        public static IList<T> getAllMediaData<T>(int mediaType,int page,int pageSize)
        {
            IList<T> dataList = new List<T>();
            StringBuilder url = new StringBuilder();
            String timeStamp = DateTool.GetCurrentTimeStamp();//获取当前时间的时间戳
            //解析cookie中用于参数的字段
            CookieContainer cookieCollectionByString = MyCookie.GetCookieCollectionByString(DT.Cookie, "pub.alimama.com");
            String token = MyCookie.GetCookie("_tb_token_", cookieCollectionByString);
            if (APP_MEDIA_TYPE == mediaType)//app媒体
            {
                url.Append("http://pub.alimama.com/common/site/appSiteManage2.json?tab=3&_input_charset=utf-8&toPage=").Append(page).Append("&perPageSize=").Append(pageSize).Append("&t=").Append(timeStamp).Append("&_tb_token_=").Append(DT.Cookie);
            }
            else if (WEB_MEDIA_TYPE == mediaType)//web媒体
            {
                url.Append("http://pub.alimama.com/common/site/webSiteManage.json?tab=1&_input_charset=utf-8&toPage=").Append(page).Append("&perPageSize=").Append(pageSize).Append("&t=").Append(timeStamp).Append("&_tb_token_=").Append(DT.Cookie);
            }
            else if (GUIDE_MEDIA_TYPE == mediaType)
            {
                url.Append("http://pub.alimama.com/common/site/generalize/guideList.json?_input_charset=utf-8&t=").Append(timeStamp).Append("&_tb_token_=").Append(DT.Cookie);
            }
            else
            {
                AddLogs("不能被识别的媒体类型："+mediaType);
                return dataList;
            }

            StringBuilder header = new StringBuilder();
            header.Append("User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36\r\n");
            header.Append("Content-Type:application/x-www-form-urlencoded; charset=UTF-8\r\n");
            header.Append("Accept:application/json, text/javascript, */*; q=0.01\r\n");
            header.Append("Accept-Encoding:gzip, deflate\r\n");
            header.Append("Accept-Language:zh-CN,zh;q=0.8\r\n");
            header.Append("Host: pub.alimama.com\r\n");
            header.Append("Origin:http://pub.alimama.com\r\n");
            header.Append("X-Requested-With:XMLHttpRequest\r\n");
            header.Append("Cookie:" + DT.Cookie);
            Wininet wininet = new Wininet();
            String respBody = wininet.PostData(url.ToString(), null, header);
            //web  {"data":{"paginator":{"length":6,"offset":0,"page":1,"beginIndex":1,"endIndex":6,"items":6,"pages":1,"itemsPerPage":40,"firstPage":1,"lastPage":1,"previousPage":1,"nextPage":1,"slider":[1]},"maxSiteNum":50,"nosite":false,"siteList":[{"name":"择天惠web","properties":null,"type":"42501","reason":null,"description":"择天惠web","flag":null,"status":"P","url":"http://www.zetianhui.com","comments":null,"siteid":40968507,"siteType":0,"memberid":110367295,"gcid":0,"autoGeneratedSite":false,"propsMap":{"recordno":"鄂ICP备14012609号-2"},"recordno":"鄂ICP备14012609号-2","updatetime":"2017-12-14","fromwhere":null,"createtime":"2017-12-14","typename":"导购分享","refusereason":null,"createtimefrom":null,"createtimeto":null,"timefrom":null,"timeto":null,"sitestat":30,"needRemind":false,"clickperday":null,"pvperday":null,"totalclick":null,"totalpv":null,"auditnum":0,"alexarank":null,"unactivecount":null,"updatetimeDateStr":"2017-12-14","updatetimeTimeStr":"16:25:40","commentsString":null,"channelCount":0,"wirelessadzoneCount":0,"appPlatform":null,"previousPage":1,"nextPage":0,"toPage":1,"perPageSize":10,"startRow":0,"totalItem":0,"totalPage":0,"firstPage":true,"orderStr":null,"lastPage":false,"endRow":0},{"name":"择天惠wap","properties":null,"type":"42501","reason":null,"description":"择天惠wap","flag":null,"status":"P","url":"http://m.zetianhui.com","comments":null,"siteid":40948829,"siteType":0,"memberid":110367295,"gcid":0,"autoGeneratedSite":false,"propsMap":{"recordno":"鄂ICP备14012609号-2"},"recordno":"鄂ICP备14012609号-2","updatetime":"2017-12-14","fromwhere":null,"createtime":"2017-12-14","typename":"导购分享","refusereason":null,"createtimefrom":null,"createtimeto":null,"timefrom":null,"timeto":null,"sitestat":30,"needRemind":false,"clickperday":null,"pvperday":null,"totalclick":null,"totalpv":null,"auditnum":0,"alexarank":null,"unactivecount":null,"updatetimeDateStr":"2017-12-14","updatetimeTimeStr":"16:24:01","commentsString":null,"channelCount":0,"wirelessadzoneCount":0,"appPlatform":null,"previousPage":1,"nextPage":0,"toPage":1,"perPageSize":10,"startRow":0,"totalItem":0,"totalPage":0,"firstPage":true,"orderStr":null,"lastPage":false,"endRow":0},{"name":"越会买-3g版本","properties":null,"type":"42501","reason":null,"description":"淘客导购3g版本","flag":null,"status":"P","url":"http://m.yuehuimai.com","comments":null,"siteid":10380355,"siteType":0,"memberid":110367295,"gcid":0,"autoGeneratedSite":false,"propsMap":{"recordno":"鄂ICP备14012609号-2"},"recordno":"鄂ICP备14012609号-2","updatetime":"2015-07-23","fromwhere":null,"createtime":"2015-07-23","typename":"导购分享","refusereason":null,"createtimefrom":null,"createtimeto":null,"timefrom":null,"timeto":null,"sitestat":30,"needRemind":false,"clickperday":null,"pvperday":null,"totalclick":null,"totalpv":null,"auditnum":0,"alexarank":null,"unactivecount":null,"updatetimeDateStr":"2015-07-23","updatetimeTimeStr":"16:50:25","commentsString":null,"channelCount":0,"wirelessadzoneCount":0,"appPlatform":null,"previousPage":1,"nextPage":0,"toPage":1,"perPageSize":10,"startRow":0,"totalItem":0,"totalPage":0,"firstPage":true,"orderStr":null,"lastPage":false,"endRow":0},{"name":"越会买pc站点","properties":null,"type":"42501","reason":null,"description":"网站导航","flag":null,"status":"P","url":"http://www.yuehuimai.com","comments":"<br/>网站打开缓慢或无法访问，详情请见：http://help.alimama.com/?spm=a2321.7393627.a214tr8.19.ovGey4#!/u/faq/detail?id=5835959","siteid":9922972,"siteType":0,"memberid":110367295,"gcid":0,"autoGeneratedSite":false,"propsMap":{"recordno":"鄂ICP备14012609号-2"},"recordno":"鄂ICP备14012609号-2","updatetime":"2015-06-09","fromwhere":null,"createtime":"2015-06-07","typename":"导购分享","refusereason":null,"createtimefrom":null,"createtimeto":null,"timefrom":null,"timeto":null,"sitestat":30,"needRemind":false,"clickperday":null,"pvperday":null,"totalclick":null,"totalpv":null,"auditnum":1,"alexarank":null,"unactivecount":null,"updatetimeDateStr":"2015-06-09","updatetimeTimeStr":"10:14:34","commentsString":null,"channelCount":0,"wirelessadzoneCount":0,"appPlatform":null,"previousPage":1,"nextPage":0,"toPage":1,"perPageSize":10,"startRow":0,"totalItem":0,"totalPage":0,"firstPage":true,"orderStr":null,"lastPage":false,"endRow":0},{"name":"手机导航","properties":null,"type":"42201","reason":null,"description":"手机导航","flag":null,"status":"P","url":"http://m.duo123.cn","comments":null,"siteid":9518509,"siteType":0,"memberid":110367295,"gcid":0,"autoGeneratedSite":false,"propsMap":{"recordno":"鄂ICP备11004134号-3"},"recordno":"鄂ICP备11004134号-3","updatetime":"2015-04-24","fromwhere":null,"createtime":"2015-04-23","typename":"网址站","refusereason":null,"createtimefrom":null,"createtimeto":null,"timefrom":null,"timeto":null,"sitestat":30,"needRemind":false,"clickperday":null,"pvperday":null,"totalclick":null,"totalpv":null,"auditnum":0,"alexarank":null,"unactivecount":null,"updatetimeDateStr":"2015-04-24","updatetimeTimeStr":"15:38:34","commentsString":null,"channelCount":0,"wirelessadzoneCount":0,"appPlatform":null,"previousPage":1,"nextPage":0,"toPage":1,"perPageSize":10,"startRow":0,"totalItem":0,"totalPage":0,"firstPage":true,"orderStr":null,"lastPage":false,"endRow":0},{"name":"精品导航","properties":null,"type":"42201","reason":null,"description":"导航网站","flag":null,"status":"P","url":"http://www.duo123.cn","comments":"<br/>违反《阿里妈妈推广者规范》(例如，网址站未按规范投放等)，详情请见：http://help.alimama.com/?spm=a2321.7393627.a214tr8.19.ovGey4#!/u/faq/detail?id=5836085\n“天猫”、“淘宝商城”链接至非“天猫”官方网站","siteid":9452222,"siteType":0,"memberid":110367295,"gcid":0,"autoGeneratedSite":false,"propsMap":{"recordno":"鄂ICP备11004134号-3"},"recordno":"鄂ICP备11004134号-3","updatetime":"2015-04-20","fromwhere":null,"createtime":"2015-04-17","typename":"网址站","refusereason":null,"createtimefrom":null,"createtimeto":null,"timefrom":null,"timeto":null,"sitestat":30,"needRemind":false,"clickperday":null,"pvperday":null,"totalclick":null,"totalpv":null,"auditnum":1,"alexarank":null,"unactivecount":null,"updatetimeDateStr":"2015-04-20","updatetimeTimeStr":"09:33:07","commentsString":null,"channelCount":0,"wirelessadzoneCount":0,"appPlatform":null,"previousPage":1,"nextPage":0,"toPage":1,"perPageSize":10,"startRow":0,"totalItem":0,"totalPage":0,"firstPage":true,"orderStr":null,"lastPage":false,"endRow":0}]},"info":{"message":null,"ok":true},"ok":true,"invalidKey":null}
            //app  {"data":{"paginator":{"length":1,"offset":0,"page":1,"beginIndex":1,"endIndex":1,"items":1,"pages":1,"itemsPerPage":40,"firstPage":1,"lastPage":1,"previousPage":1,"nextPage":1,"slider":[1]},"maxSiteNum":20,"nosite":false,"siteList":[{"name":"择天惠_安卓","properties":null,"type":"1024","reason":null,"description":"择天惠是一款领淘宝天猫优惠券的导购软件","flag":null,"status":"P","url":"http://m.pp.cn/detail.html?appid=7696881&ch_src=pp_dev&ch=default","comments":null,"siteType":1,"siteid":42086072,"autoGeneratedSite":false,"memberid":110367295,"gcid":7,"propsMap":{"sysFileName":"f_42086072_110367295_8C2271B002464823A72952BA1F15C48F_110_3686166d59371796910edba5b83897d7.apk","platformType":"1","showFileName":"110_3686166d59371796910edba5b83897d7.apk"},"recordno":null,"updatetime":"2018-01-22","fromwhere":null,"createtime":"2018-01-19","typename":"分享导购","timefrom":null,"timeto":null,"createtimefrom":null,"createtimeto":null,"refusereason":null,"sitestat":30,"needRemind":false,"clickperday":null,"pvperday":null,"totalclick":null,"totalpv":null,"auditnum":0,"alexarank":null,"unactivecount":null,"updatetimeDateStr":"2018-01-22","updatetimeTimeStr":"09:45:11","commentsString":null,"channelCount":0,"wirelessadzoneCount":0,"appPlatform":null,"previousPage":1,"nextPage":0,"toPage":1,"perPageSize":10,"startRow":0,"totalItem":0,"totalPage":0,"firstPage":true,"orderStr":null,"lastPage":false,"endRow":0}]},"info":{"message":null,"ok":true},"ok":true,"invalidKey":null}
            //guide {"data":{"maxSiteNum":50,"guideList":[{"name":"微信","description":null,"url":null,"comments":null,"memberID":110367295,"autoGeneratedSite":false,"sysid":null,"auditNum":0,"propsMap":{"account1":["darong2485"]},"siteType":"14","guideID":42278341,"auditorId":null,"account1":null,"account2":null,"account3":null,"usedAccountIndexs":null,"sitestat":null,"siteStatus":"P","category2":"聊天工具","category3":"微信"},{"name":"QQ_110367295","description":null,"url":null,"comments":null,"memberID":110367295,"autoGeneratedSite":false,"sysid":null,"auditNum":0,"propsMap":{"account2":[""],"account1":["2573338738"]},"siteType":"13","guideID":10234346,"auditorId":null,"account1":null,"account2":null,"account3":null,"usedAccountIndexs":null,"sitestat":null,"siteStatus":"P","category2":"聊天工具","category3":"QQ"},{"name":"爱分享(手机客户端专享)_110367295","description":null,"url":null,"comments":null,"memberID":110367295,"autoGeneratedSite":false,"sysid":null,"auditNum":0,"propsMap":{},"siteType":"1025","guideID":9976259,"auditorId":null,"account1":null,"account2":null,"account3":null,"usedAccountIndexs":null,"sitestat":null,"siteStatus":"P","category2":"分享","category3":"爱分享(手机客户端专享)"}]},"info":{"message":null,"ok":true},"ok":true,"invalidKey":null}

            return new List<T>();
        }

        private static void AddLogs(string logContent)
        {
            if (LogDisplayedInForm_.Items.Count > 300)
            {
                LogDisplayedInForm_.Items.Clear();
            }
            LogDisplayedInForm_.Items.Add(DateTime.Now.ToLongTimeString() + "=>" + logContent);
            LogDisplayedInForm_.SelectedIndex = LogDisplayedInForm_.Items.Count - 1;
        }

    }
}
